import globals from "globals";

const timeless_globals = {
  Alert: "readonly",
  AlertDescription: "readonly",
  AlertTitle: "readonly",
  Avatar: "readonly",
  Badge: "readonly",
  Button: "readonly",
  Card: "readonly",
  CardContent: "readonly",
  CardDescription: "readonly",
  CardFooter: "readonly",
  CardHeader: "readonly",
  CardTitle: "readonly",
  Checkbox: "readonly",
  DatePicker: "readonly",
  DangerouslyInnerHTML: "readonly",
  Dialog: "readonly",
  DialogBody: "readonly",
  DialogDescription: "readonly",
  DialogFooter: "readonly",
  DialogHeader: "readonly",
  DialogTitle: "readonly",
  DropdownMenu: "readonly",
  EmptyState: "readonly",
  Flex: "readonly",
  For: "readonly",
  FormField: "readonly",
  Icon: "readonly",
  IconButton: "readonly",
  Input: "readonly",
  invoke: "readonly",
  isComponent: "readonly",
  isRef: "readonly",
  Label: "readonly",
  Match: "readonly",
  MemoCard: "readonly",
  Menu: "readonly",
  Modal: "readonly",
  NavigatorCore: "readonly",
  Popover: "readonly",
  Portal: "readonly",
  Presence: "readonly",
  Progress: "readonly",
  ProjectSelect: "readonly",
  Select: "readonly",
  ScrollView: "readonly",
  Separator: "readonly",
  Show: "readonly",
  Skeleton: "readonly",
  Slider: "readonly",
  SmallCalendar: "readonly",
  Spinner: "readonly",
  Switch: "readonly",
  Table: "readonly",
  TableBody: "readonly",
  TableCell: "readonly",
  TableHead: "readonly",
  TableHeader: "readonly",
  TableRow: "readonly",
  Tabs: "readonly",
  Textarea: "readonly",
  Timeless: "readonly",
  Toggle: "readonly",
  Txt: "readonly",
  View: "readonly",
  classnames: "readonly",
  computed: "readonly",
  ref: "readonly",
};

export default [
  {
    ignores: ["node_modules/", "dist/", "build/", "public/"],
  },
  {
    files: ["index.js", "src/**/*.js"],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "module",
      globals: {
        ...globals.browser,
        ...timeless_globals,
      },
    },
    rules: {
      "no-undef": "warn",
      "no-unused-vars": [
        "warn",
        {
          args: "after-used",
          caughtErrors: "none",
          ignoreRestSiblings: true,
        },
      ],
      semi: ["warn", "always"],
      indent: [
        "warn",
        2,
        { ignoreComments: true, ignoredNodes: ["TemplateLiteral > *"] },
      ],
    },
  },
  {
    files: [
      "**/*.test.js",
      "*.config.js",
      "*.config.mjs",
      "import-map-loader.mjs",
      "register-import-map.mjs",
    ],
    languageOptions: {
      globals: {
        ...globals.browser,
        ...globals.node,
        ...timeless_globals,
      },
    },
  },
];
