import { Timeless } from "@/timeless-icons.js";

export const SVG = Object.freeze({
  archive: Timeless.Icon({ name: "archive" }),
  bell: Timeless.Icon({ name: "bell" }),
  bold: Timeless.Icon({ name: "bold" }),
  check: Timeless.Icon({ name: "check" }),
  chevronDown: Timeless.Icon({ name: "chevron-down" }),
  chevronUp: Timeless.Icon({ name: "chevron-up" }),
  chevronLeft: Timeless.Icon({ name: "chevron-left" }),
  chevronRight: Timeless.Icon({ name: "chevron-right" }),
  clock: Timeless.Icon({ name: "clock" }),
  code: Timeless.Icon({ name: "code" }),
  comment: Timeless.Icon({ name: "comment" }),
  copy: Timeless.Icon({ name: "copy" }),
  edit: Timeless.Icon({ name: "edit" }),
  external: Timeless.Icon({ name: "external-link" }),
  eye: Timeless.Icon({ name: "eye" }),
  globe: Timeless.Icon({ name: "globe" }),
  hash: Timeless.Icon({ name: "hash" }),
  image: Timeless.Icon({ name: "image" }),
  italic: Timeless.Icon({ name: "italic" }),
  link: Timeless.Icon({ name: "link" }),
  list: Timeless.Icon({ name: "list" }),
  moreHorizontal: Timeless.Icon({ name: "ellipsis" }),
  lock: Timeless.Icon({ name: "lock" }),
  paperclip: Timeless.Icon({ name: "paperclip" }),
  pin: Timeless.Icon({
    name: "pin",
    attributes: { n: "pin-icon", "data-n": "pin-icon" },
  }),
  unpin: Timeless.Icon({
    name: "unpin",
    attributes: { n: "unpin-icon", "data-n": "unpin-icon" },
  }),
  plus: Timeless.Icon({ name: "plus" }),
  reply: Timeless.Icon({ name: "reply" }),
  refresh: Timeless.Icon({ name: "refresh-cw" }),
  restore: Timeless.Icon({ name: "undo2" }),
  search: Timeless.Icon({ name: "search" }),
  smile: Timeless.Icon({ name: "smile" }),
  send: Timeless.Icon({ name: "send" }),
  settings: Timeless.Icon({ name: "settings" }),
  shield: Timeless.Icon({ name: "shield" }),
  sort: Timeless.Icon({ name: "list-filter" }),
  toc: Timeless.Icon({ name: "scroll-text" }),
  trash: Timeless.Icon({ name: "trash2" }),
  history: Timeless.Icon({ name: "history" }),
  x: Timeless.Icon({ name: "x" }),
  columns: Timeless.Icon({ name: "columns" }),
  workflow: Timeless.Icon({ name: "workflow" }),
  mapPin: Timeless.Icon({ name: "map-pin" }),
});
